version: '3'

volumes:
    appenv:
        driver: local

services:
  db:
    image: postgres
  
  web_blog:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: python3 manage.py runserver 0:8000
    volumes:
      - ../blog:/app
      - appenv:/appenv
    ports:
      - '8000:8000'
    depends_on:
      - db

  # adhoc:
  #   build:
  #     context: ../
  #     dockerfile: docker/Dockerfile
  #   volumes:
  #     - appenv:/appenv
  #   depends_on:
  #     - db
